F19-4900-Group1/learnfast/learnfast/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopping_cart/', include('shopping_cart.urls', namespace="shopping_cart")),
    path('', include('sis.urls')),
    path('', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

F19-4900-Group1/learnfast/shopping_cart/urls.py
from django.conf.urls import url
from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    process_payment,
    update_transaction_records,
    success
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name="delete_item"),
    url(r'^checkout/$', checkout, name='checkout'),
    #url(r'^payment/(?P<order_id>[-\w]+)/$', process_payment, name="process_payment"),
    url(r'^update-transaction/(?P<order_id>[-\w]+)/$', update_transaction_records, name="update_records"),
]

F19-4900-Group1/learnfast/sis/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'sis'
urlpatterns = [
    path('', views.student_home, name='student_home'),
    #re_path(r'^home/$', views.home, name='home'),
    path('tutor_list', views.tutor_list, name='tutor_list'),
    path('course_list', views.course_list, name='course_list'),
    path('schedule_list', views.schedule_list, name='schedule_list'),
    path('register/', views.register, name='register'),
]

F19-4900-Group1/learnfast/sis/models.py
from django.db import models
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save

# Create your models here.
class Student(models.Model):
    stud_name = models.CharField(max_length=100)
    stud_address = models.CharField(max_length=200)
    stud_city = models.CharField(max_length=50)
    stud_zip = models.CharField(max_length=10)
    stud_email = models.CharField(max_length=50)
    stud_phone = models.CharField(max_length=50)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.stud_name)

class Tutor(models.Model):
    tutor_id = models.IntegerField(primary_key=True, default=0)
    tutor_name = models.CharField(max_length=100)
    tutor_address = models.CharField(max_length=200)
    tutor_city = models.CharField(max_length=50)
    tutor_zip = models.CharField(max_length=10)
    tutor_email = models.CharField(max_length=50)
    tutor_phone = models.CharField(max_length=50)
    tutor_sub_expertise = models.CharField(max_length=50)
    tutor_bank = models.CharField(max_length=100)
    tutor_rt_num = models.CharField(max_length=10)
    tutor_acct_num = models.CharField(max_length=100)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.tutor_name)

class Course(models.Model):
    course_id = models.IntegerField(primary_key=True, default=0)
    course_name = models.CharField(max_length=100)
    course_description = models.TextField(blank=True)
    course_subject = models.CharField(max_length=50)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)


    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.course_name)

class Room(models.Model):
    room_id = models.IntegerField(primary_key=True, default=0)
    room_number = models.CharField(max_length=100)
    room_capacity = models.IntegerField()
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)


    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.room_number)

class Schedule(models.Model):
    schedule_id = models.IntegerField()
    #schedule_course_name = models.CharField(max_length=100)
    schedule_course_name = models.ForeignKey(Course, related_name='contents', on_delete=models.CASCADE)
    schedule_room_number = models.ForeignKey(Room, related_name='contents', on_delete=models.CASCADE)
    schedule_tutor_name = models.ForeignKey(Tutor, related_name='contents', on_delete=models.CASCADE)
    schedule_date = models.DateField()
    schedule_time = models.TimeField()
    schedule_notes = models.TextField(blank=True)
    slug = models.SlugField(max_length=200, db_index=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now_add=True)
#    max_seat = models.IntegerField()


    def created(self):
        self.created = timezone.now()
        self.save()

    def updated(self):
        self.updated = timezone.now()
        self.save()

    def __str__(self):
        return str(self.schedule_course_name)


User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    schedules = models.ManyToManyField(Schedule, blank=True)

    def __str__(self):
        return self.user.username


def post_save_profile_create(sender, instance, created, *args, **kwargs):
    if created:
        Profile.objects.get_or_create(user=instance)


post_save.connect(post_save_profile_create, sender=settings.AUTH_USER_MODEL)

F19-4900-Group1/learnfast/sis/forms.py
from django import forms
from .models import Course, Tutor
from django.contrib.auth.models import User, Group

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('course_name', 'course_description', 'course_subject')

class TutorForm(forms.ModelForm):
    class Meta:
        model = Tutor
        fields = ('tutor_name', 'tutor_address', 'tutor_city', 'tutor_zip', 'tutor_email', 'tutor_phone', 'tutor_sub_expertise')

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

F19-4900-Group1/learnfast/sis/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from shopping_cart.models import Order
from .forms import UserRegistrationForm
from django.contrib.auth.models import Group


now = timezone.now()
def student_home(request):
    return render(request, 'sis/student_home.html', {'sis':student_home})

@login_required
def tutor_list(request):
    tutor = Tutor.objects.filter(created_date__lte=timezone.now())
    return render(request, 'sis/tutor_list.html', {'tutors': tutor})

@login_required
def course_list(request):
    course = Course.objects.filter(created_date__lte=timezone.now())
    return render(request, 'sis/course_list.html', {'courses': course})

@login_required
def schedule_list(request):
    object_list = Schedule.objects.all()
    filtered_orders = Order.objects.filter(owner=request.user.profile, is_ordered=False)
    current_order_schedules = []
    if filtered_orders.exists():
        user_order = filtered_orders[0]
        user_order_items = user_order.items.all()
        current_order_schedules = [schedule.schedule for schedule in user_order_items]

    context = {
        'object_list': object_list,
        'current_order_schedules': current_order_schedules
    }

    return render(request, "sis/schedule_list.html", context)

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            group = Group.objects.get(name='student')
            # Set the chosen password
            new_user.set_password(
                user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request,
                          'sis/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'sis/register.html',
                  {'user_form': user_form})

def my_profile(request):
    my_user_profile = Profile.objects.filter(user=request.user).first()
    my_orders = Order.objects.filter(is_ordered=True, owner=my_user_profile)
    context = {
        'my_orders':my_orders
    }
    return render(request, "profile.html", context)

F19-4900-Group1/learnfast/sis/templates/sis/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learn Fast Tutoring</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/portfolio.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body id="app-layout">
    <nav class="navbar-expand-md bg-success navbar-light">
        <div class="container-fluid">
            <div class="navbar-header">
               <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                   <!-- Branding Image -->
                <a class="navbar-brand" href="/">Learn Fast</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="">About Us</a>
                    </li>
                    <li>
                        <a href="">Dashboard</a>
                    </li>
                    <li>
                        <a href="{% url 'sis:schedule_list' %}">Enroll</a>
                    </li>
                    <li>
                        <a href="">Contact Us</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li class="dropdown">
                             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{% url 'logout' %}">
                                        <i class="fa fa-btn fa-sign-out"></i>Logout
                                    </a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% block content %}
                    <div class="links">
                         <!-- Example row of columns -->
                        <div class="row">
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href=""><img src="{% static "image/about_us.png" %}" alt="about us"/></a>
                                    <div class="caption">
                                        <h3>About Us</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'sis:schedule_list' %}"><img src="{% static "image/enroll.jpg" %}" alt="enroll"/></a>
                                    <div class="caption">
                                        <h3>Enroll</h3>
                                        {% if user.is_authenticated %}
                                            <p><a class="btn btn-default" href="{% url 'sis:schedule_list'%}" role="button">Click to View Classes &raquo;</a></p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href=""><img src="{% static "image/contact_us.jpg" %}" alt="contact us"/></a>
                                    <div class="caption">
                                        <h3>Contact Us</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

F19-4900-Group1/learnfast/sis/templates/sis/course_list.html
{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Learn Fast</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {background-color: beige;}
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Learn Fast For a Better Future!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Course Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr class="bg-info">
                    <th>Course</th>
                    <th>Description</th>
                    <th>Subject Category</th>
                    <th colspan="3">Summary</th>
                </tr>
            </thead>
            <tbody>
            {% for course in courses %}
                <tr>
                    <td>{{ course.course_name }}</td>
                    <td>{{ course.course_description }}</td>
                    <td>{{ course_subject }}</td>
                    <td><a href="" class="btn btn-primary">Summary</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    </body>
    </html>
{% endblock %}

F19-4900-Group1/learnfast/sis/templates/sis/home.html
<!DOCTYPE html>
<html lang="en">
{% extends 'sis/base.html' %}
{% load staticfiles %}
{% block content %}
    <body>
        {% if user.is_authenticated %}
            <div class="container">
                <h2 class="top-menu">Hello {{ user.username }},</h2>
                <p>Please choose from below options.</p>
            </div>
        {% endif %}
        <div class="content container">
            <div class="row">
                <div class="col-md-12">
                    <div class="links">
                        <!-- Example row of columns -->
                        <div class="row">
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href=""><img src="{% static "image/dashboard.png" %}" alt="dashboard"/></a>
                                    <div class="caption">
                                        <h3>Dashboard</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'sis:schedule_list' %}"><img src="{% static "image/enroll.jpg" %}" alt="enroll"/></a>
                                    <div class="caption">
                                        <h3>Enroll</h3>
                                        {% if user.is_authenticated %}
                                            <p><a class="btn btn-default" href="{% url 'sis:schedule_list'%}" role="button">Click to View Classes &raquo;</a></p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href=""><img src="{% static "image/checkout.png" %}" alt="checkout"/></a>
                                    <div class="caption">
                                        <h3>Checkout</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
{% endblock %}


</html>

F19-4900-Group1/learnfast/sis/templates/sis/register.html
{% extends "sis/base.html" %}

{% block title %}Create an account{% endblock %}

{% block content %}
  <h1>Create an account</h1>
  <p>Please, sign up using the following form:</p>
  <form action="." method="post">
    {{ user_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Create my account"></p>
  </form>
{% endblock %}

F19-4900-Group1/learnfast/sis/templates/sis/register_done.html
{% extends "sis/base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
  <h1>Welcome {{ new_user.first_name }}!</h1>
  <p>Your account has been successfully created. Now you can <a href="{% url "login" %}">log in</a>.</p>
{% endblock %}

F19-4900-Group1/learnfast/sis/templates/sis/schedule_list.html
 <!DOCTYPE html>
<html lang="en">
{% extends 'sis/base.html' %}
{% block content %}
    <head>
        <meta charset="UTF-8">
        <title>Learn Fast</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    </head>
    <body>
    <style>
        body {background-color: beige;}
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Learn Fast For a Better Future!
                    </div>
                </div>
            </div>
        </div>
    </div>
<!--    <div class="row">-->
<!--        <h2 style="padding-left: 15Px">Schedule Information</h2>-->
<!--    </div>-->
<!--    <div>-->
<!--        <table class="table table-striped table-bordered table-hover">-->
<!--            <thead>-->
<!--                <tr class="bg-info">-->
<!--                    <th>Schedule</th>-->
<!--                    <th>Course</th>-->
<!--                    <th>Tutor</th>-->
<!--                    <th>Room</th>-->
<!--                    <th>Date</th>-->
<!--                    <th>Time</th>-->
<!--                    <th>Max Seat</th>-->
<!--                    <th colspan="3">Actions</th>-->
<!--                </tr>-->
<!--            </thead>-->
<!--            <tbody>-->
<!--            {% for tutor in tutors %}-->
<!--                <tr>-->
<!--                    <td>{{ schedule.schedule_id }}</td>-->
<!--                    <td>{{ schedule.schedule_course_name }}</td>-->
<!--                    <td>{{ schedule.schedule_tutor_name }}</td>-->
<!--                    <td>{{ schedule.schedule_room_number }}</td>-->
<!--                    <td>{{ schedule.schedule_date }}</td>-->
<!--                    <td>{{ schedule.schedule_time }}</td>-->
<!--                    <td><a href="" class="btn btn-primary">Enroll</a></td>-->
<!--                    <td><a href="" class="btn btn-primary">Summary</a></td>-->
<!--                </tr>-->
<!--            {% endfor %}-->
<!--            </tbody>-->
<!--        </table>-->
<!--    </div>-->
    {{message}}
    <div class="row">
    {% for object in object_list %}
        <div class="col-sm-3">
            <p>{{ object.schedule_course_name }}</p>
            <p>{{ object.schedule_tutor_name}}</p>
            <p>{{ object.schedule_date}}</p>
            <p>{{ object.schedule_time}}</p>
            <p>Price: ${{ object.price }}</p>
            {% if object in current_order_schedules %}
            <a href="{% url 'shopping_cart:order_summary' %}" class="btn btn-warning">Go to Cart</a>
            {% else %}
            <a href="{% url 'shopping_cart:add_to_cart' object.id %}" class="btn btn-warning">Add to Cart</a>
            {% endif %}
        </div>
    {% endfor %}
    </div>
    </body>
    </html>
{% endblock %}

F19-4900-Group1/learnfast/sis/templates/sis/student_home.html
<!DOCTYPE html>
<html lang="en">
{% extends 'sis/base.html' %}
{% load staticfiles %}
{% block content %}
    <body>
        {% if user.is_authenticated %}
            <div class="container">
                <h2 class="top-menu">Hello {{ user.username }},</h2>
                <p>Please choose from below options.</p>
            </div>
        {% endif %}
        <div class="content container">
            <div class="row">
                <div class="col-md-12">
                    <div class="links">
                        <!-- Example row of columns -->
                        <div class="row">
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href=""><img src="{% static "image/dashboard.png" %}" alt="dashboard"/></a>
                                    <div class="caption">
                                        <h3>Dashboard</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'sis:schedule_list' %}"><img src="{% static "image/enroll.jpg" %}" alt="enroll"/></a>
                                    <div class="caption">
                                        <h3>Enroll</h3>
                                        {% if user.is_authenticated %}
                                            <p><a class="btn btn-default" href="{% url 'sis:schedule_list'%}" role="button">Click to View Classes &raquo;</a></p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'shopping_cart:order_summary' %}"><img src="{% static "image/checkout.png" %}" alt="checkout"/></a>
                                    <div class="caption">
                                        <h3>Checkout</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
{% endblock %}


</html>

F19-4900-Group1/learnfast/sis/templates/sis/tutor_list.html
{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Learn Fast</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {background-color: beige;}
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Learn Fast For a Better Future!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Tutor Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr class="bg-info">
                    <th>Tutor Name</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>Zip Code</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Subject Expertise</th>
                    <th colspan="3">Summary</th>
                </tr>
            </thead>
            <tbody>
            {% for tutor in tutors %}
                <tr>
                    <td>{{ tutor.tutor_name }}</td>
                    <td>{{ tutor.tutor_address }}</td>
                    <td>{{ tutor.tutor_city }}</td>
                    <td>{{ tutor.tutor_zip }}</td>
                    <td>{{ tutor.tutor_email }}</td>
                    <td>{{ tutor.tutor_phone }}</td>
                    <td>{{ tutor.tutor_sub_expertise }}</td>
                    <td><a href="" class="btn btn-primary">Summary</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    </body>
    </html>
{% endblock %}