F19-4900-Group1/learnfast/learnfast/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopping_cart/', include('shopping_cart.urls', namespace="shopping_cart")),
    path('', include('sis.urls')),
    path('', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

F19-4900-Group1/learnfast/shopping_cart/urls.py
from django.conf.urls import url
from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    process_payment,
    update_transaction_records,
    success
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name="delete_item"),
    url(r'^checkout/$', checkout, name='checkout'),
    #url(r'^payment/(?P<order_id>[-\w]+)/$', process_payment, name="process_payment"),
    url(r'^update-transaction/(?P<order_id>[-\w]+)/$', update_transaction_records, name="update_records"),
]

F19-4900-Group1/learnfast/sis/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'sis'
urlpatterns = [
    path('', views.student_home, name='student_home'),
    #re_path(r'^home/$', views.home, name='home'),
    path('tutor_list', views.tutor_list, name='tutor_list'),
    path('course_list', views.course_list, name='course_list'),
    path('schedule_list', views.schedule_list, name='schedule_list'),
    path('register/', views.register, name='register'),
]

F19-4900-Group1/learnfast/shopping_cart/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

from sis.models import Profile, Schedule

class OrderItem(models.Model):
    schedule = models.OneToOneField(Schedule, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return str(self.schedule.schedule_course_name)

class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    #payment_details = models.ForeignKey(Payment, null=True)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.schedule.price for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)

class Transaction(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    token = models.CharField(max_length=120)
    order_id = models.CharField(max_length=120)
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    success = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.order_id

    class Meta:
        ordering = ['-timestamp']

F19-4900-Group1/learnfast/shopping_cart/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404

from sis.models import Profile, Schedule

from shopping_cart.extras import generate_order_id
from shopping_cart.models import OrderItem, Order, Transaction

import datetime



def get_user_pending_order(request):
    # get order for the correct user
    user_profile = get_object_or_404(Profile, user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)
    #print(order)
    if order.exists():
        # get the only order in the list of filtered orders
        #print(order[0])
        return order[0]
    return 0

@login_required()
def add_to_cart(request, **kwargs):
    user_profile = get_object_or_404(Profile, user=request.user)
    schedule = Schedule.objects.filter(id=kwargs.get('item_id', "")).first()
    order_item, status = OrderItem.objects.get_or_create(schedule=schedule)
    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        # generate a reference code
        user_order.ref_code = generate_order_id()
        user_order.save()

    # show confirmation message and redirect back to the same page
    messages.info(request, "item added to cart")
    return redirect(reverse('sis:schedule_list'))

@login_required()
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Item has been deleted")
    return redirect(reverse('shopping_cart:order_summary'))

@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order
    }
    return render(request, 'shopping_cart/order_summary.html', context)

@login_required()
def checkout(request):
    existing_order = get_user_pending_order(request)
    context = {
        'order':existing_order,
    }
    type(existing_order)
    print(context)
    return render(request, 'shopping_cart/checkout.html', context)

@login_required()
def process_payment(request, order_id):
    return redirect(reverse('shopping_cart:update_records',
                            kwargs={
                                'order_id':order_id,
                            })
                    )


@login_required()
def update_transaction_records(request, token):
    # get the order being processed
    order_to_purchase = get_user_pending_order(request)

    # update the placed order
    order_to_purchase.is_ordered = True
    order_to_purchase.date_ordered = datetime.datetime.now()
    order_to_purchase.save()

    # get all items in the order - generates a queryset
    order_items = order_to_purchase.items.all()

    # update order items
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())

    # Add products to user profile
    user_profile = get_object_or_404(Profile, user=request.user)
    # get the products from the items
    order_schedules = [item.schedule for item in order_items]
    user_profile.schedules.add(*order_schedules)
    user_profile.save()

    # create a transaction
    transaction = Transaction(profile=request.user.profile,
                              token=token,
                              order_id=order_to_purchase.id,
                              amount=order_to_purchase.get_cart_total(),
                              success=True)
    # save the transcation (otherwise doesn't exist)
    transaction.save()

    # send an email to the customer
    # look at tutorial on how to send emails with sendgrid
    messages.info(request, "Thank you! Your purchase was successful!")
    return redirect(reverse('accounts:my_profile'))


def success(request, **kwargs):
    # a view signifying the transcation was successful
    return render(request, 'shopping_cart/purchase_success.html', {})

F19-4900-Group1/learnfast/shopping_cart/templates/shopping_cart/checkout.html
{% extends "sis/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
<!--    <meta charset="UTF-8">-->
<!--    <title>Checkout</title>-->
<!--    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" type="text/css" rel="stylesheet">-->
<!--    <link rel="stylesheet" type="text/css" href="{% static 'css/checkout.css' %}">-->
<!--    <style>-->
<!--      #checkoutMethods {-->
<!--        background: #fff;-->
<!--        border-radius: 2px;-->
<!--        display: inline-block;-->
<!--        max-height: 700px;-->
<!--        margin: 1rem;-->
<!--        position: relative;-->
<!--        width: 700px;-->
<!--        box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);-->
<!--      }-->
<!--    </style>-->
</head>

<body>
    <div class="container">
    <section>
      <div class="col-md-8 col-xs-12">
        <table class="table">
          <tr>
            <td><h4>Order Summary</h4></td>
          </tr>
          <tr>
            <td>
              {% for item in order.get_cart_items %}
                <tr>
                  <td>{{ item }}</td>
                  <td>${{ item.schedule.price }}</td>
                </tr>
              {% endfor %}
            </td>
          </tr>
          <tr>
            <td><strong>Order Total</strong> </td>
            <td> <strong>${{ order.get_cart_total }}</strong></td>
          </tr>
        </table>
          <form method="POST" action=".">
              {% csrf_token %}
              <button class="btn btn-warning">Pay with card</button>
          </form>
      </div>
    </section>

</body>
</html>
{% endblock %}

F19-4900-Group1/learnfast/shopping_cart/templates/shopping_cart/order_summary.html
{% extends "sis/base.html" %}

{% block content %}

 <section>
   <div class="row">
    <table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>no.</th>
        <th>Item</th>
        <th>Price</th>
      </tr>
      {% for item in order.get_cart_items %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            {{ item.schedule.schedule_course_name }}
            <span class="pull-right">
              <a href="{% url 'shopping_cart:delete_item' item.id %}" data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_delete();">
                <i class="fas fa-trash"></i>
              </a>
            </span>
          </td>
          <td>{{ item.schedule.price }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan= 3> You have not added any items yet.</td>
        </tr>
      {% endfor %}
      <tr>
        {% if order.get_cart_total != None %}
        <td colspan=2>
          <strong class="pull-right">Order Total:</strong>
        </td>
        
        <td colspan= 1>
          $<strong>{{ order.get_cart_total }}</strong>
        </td>
        {% endif %}
      </tr>
      <tr>
        <td colspan=1 >
          <a href="{% url 'sis:schedule_list' %}" class="btn btn-warning pull-left">
            {% if order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a> 
        </td>
        <td colspan=2>
          {% if order.get_cart_items %}
            <a href="{% url 'shopping_cart:checkout' %}" class="pull-right btn btn-primary">Proceed To Checkout</a>
          {% endif %}
        </td>
      </tr>
    </table>
     
   </div>
 </section>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script>
  function confirm_delete(){
    return confirm("Do you want to remove this item from cart?");
  }
  </script>
{% endblock scripts %}

F19-4900-Group1/learnfast/shopping_cart/templates/shopping_cart/purchase_success.html
{% extends 'sis/base.html' %}

{% block content %}
    <h1>Thank you for your purchase!</h1>
    <a href="{% url 'sis:schedule_list' %}">Head back home</a>
{% endblock content %}